### ISSUE TITLE
can not find qt support 

### ISSUE THREAD

**Issue by mizhang** [sipa/bitcoin#65]
Hi, 

I am trying to run ./configure. 

got error message "qt support requested but qt could not be located. use --without-qt"

I have another project cloned from bitcoin/bitcoin at github.  That project runs fine with ./configure. 

I am using online free license QA creator.  

Any ideas about what might causes me problems

Thanks.

**Comment by sipa** [comment]
This sounds like a problem to report upstream: https://github.com/bitcoin/bitcoin/issues.
